#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  8 09:30:59 2021

@author: leo
"""
from Recommender.Algorithm import Recommender

#from data_handling.handle_data import *
from data_handling.handle_data import get_anime,get_users_ratings
from data_handling.handle_data import get_virgin_data, drop_users_with_too_many_items
from data_handling.handle_data import replace_rating_with_0_and_1
from data_handling.handle_data import get_titles,get_my_ratings
from data_handling.handle_data import drop_users_with_high_proportion_of_ratings


control_group = [7674,5630,395,37520,457,2418,34565,37517,6,16201,31240]

# -1 is me, Mario!
MY_USER_ID = -1

df_anime = get_anime()

ratings = get_users_ratings()
anime_titles = get_titles()
my_ratings = get_my_ratings()

ratings_with_me = ratings.append(my_ratings).fillna(MY_USER_ID )

data_virgin = get_virgin_data(ratings_with_me, df_anime, 5,0)

ITEMS_THRESHOLD = 500
data_too_many_watched = drop_users_with_too_many_items(data_virgin, ITEMS_THRESHOLD )

data_without_happy_users  = drop_users_with_high_proportion_of_ratings(data_too_many_watched,
                                                                        threshold=0.9)
data_extreme_like_or_not = replace_rating_with_0_and_1(data_without_happy_users)
#data = pd.read_csv(PATH_REPLACED_RATINGS, usecols=['user','item','rating'])
data_final = data_extreme_like_or_not
pivot = data_final.pivot(columns='user',index='item').rating
#train, test = split_df(data)
USER = -1
MIN_ITEMS = 25
alg = Recommender(data_final, USER, min_items=MIN_ITEMS,titles=anime_titles)
#k,p = best_knn(alg)
#print(k,p)
#alg = Recommender(train , user, min_items=min_items,titles=anime_titles)
#alg = Recommender(data, user, min_items=min_items,titles=anime_titles)
recs_cols = ['item','recs']
# t,p,n = alg.recs(anime_titles.item,20,0.75)
# df = pd.DataFrame(t, columns=recs_cols)
# df = df.sort_values('recs', ascending=False)
